# Generated by Django 3.1.2 on 2020-10-23 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squirrelapp', '0006_auto_20201019_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirreldetails',
            name='Date',
            field=models.CharField(max_length=10),
        ),
    ]
